sudo: required

servies:
- docker

jobs:
  include:
  - stage: build
    env:
    - VERSION=7.2
    script:
    - echo "${DOCKER_PASSWORD}" | docker login -u $DOCKER_USERNAME --password-stdin
    - docker build -t dockerizr/grunt-php-builder:${VERSION} ./${VERSION}
    - docker tag dockerizr/grunt-php-builder:${VERSION} dockerizr/grunt-php-builder:latest
    - docker push dockerizr/grunt-php-builder:${VERSION}
    - docker push dockerizr/grunt-php-builder:latest
  - env:
    - VERSION=7.1
    script:
    - echo "${DOCKER_PASSWORD}" | docker login -u $DOCKER_USERNAME --password-stdin
    - docker build -t dockerizr/grunt-php-builder:${VERSION} ./${VERSION}
    - docker push dockerizr/grunt-php-builder:${VERSION}
  - env:
    - VERSION=7.0
    script:
    - echo "${DOCKER_PASSWORD}" | docker login -u $DOCKER_USERNAME --password-stdin
    - docker build -t dockerizr/grunt-php-builder:${VERSION} ./${VERSION}
    - docker push dockerizr/grunt-php-builder:${VERSION}
  - env:
    - VERSION=5.6
    script:
    - echo "${DOCKER_PASSWORD}" | docker login -u $DOCKER_USERNAME --password-stdin
    - docker build -t dockerizr/grunt-php-builder:${VERSION} ./${VERSION}
    - docker push dockerizr/grunt-php-builder:${VERSION}
